run:
    LOCALLY
    
    DO +DEPS

    RUN kind create cluster --name earthlydemo

    RUN kubectl apply -f buildkit.yaml
    RUN kubectl wait --for=condition=available deployment/earthly-buildkitd              --timeout 90s
    RUN kubectl wait --for=condition=ready     pod -l component=buildkitd -l app=earthly --timeout=90s

    RUN kubectl apply -f earthly.yaml
    RUN kubectl wait --for=condition=ready     pod -l component=earthly -l app=earthly --timeout=90s

    RUN kubectl logs -f jobs/earthly

    DO +CLEANUP

clean:
    LOCALLY

    DO +DEPS
    DO +CLEANUP


DEPS:
    COMMAND
    # Ensure local dependencies are present
    RUN which kind && which kubectl

CLEANUP:
    COMMAND
    RUN kind delete cluster --name earthlydemo || true